name: cxx-ci 
on: 
  workflow_call: 
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v4 
      - name: Install deps 
        run: | 
          sudo apt-get update 
          sudo apt-get install -y cmake ninja-build 
      - name: Configure 
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release 
      - name: Build 
        run: cmake --build build --config Release -j 
      - name: Tests 
        run: ctest --test-dir build --output-on-failure
